AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rust-lmi-demo
  An AWS Serverless Application Model (SAM) template for a Rust-based Lambda function using Lambda Managed Instances (LMI) capacity provider.
Parameters:
  ManagedInstancesSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs for the Lambda Managed Instances capacity provider
  ManagedInstancesSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID for the Lambda Managed Instances capacity provider

Globals:
  Function:
    Timeout: 30
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: INFO
  Api:
    TracingEnabled: true

Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      TracingEnabled: true
      EndpointConfiguration: REGIONAL
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          DataTraceEnabled: true
          LoggingLevel: INFO
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","path":"$context.path","status":"$context.status","responseLatency":"$context.responseLatency","integrationLatency":"$context.integrationLatency"}'

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${AWS::StackName}-access-logs"
      RetentionInDays: 7

  HelloWorldFunction512:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      FunctionName: !Sub ${AWS::StackName}-512
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Architectures:
      - arm64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref HelloWorldApi
            Path: /default/512/hello
            Method: get
  
  HelloWorldFunction128:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      FunctionName: !Sub ${AWS::StackName}-128
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 128
      Architectures:
      - arm64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref HelloWorldApi
            Path: /default/128/hello
            Method: get

  CapacityProvider:
    Type: AWS::Serverless::CapacityProvider
    Properties:
      CapacityProviderName: !Sub ${AWS::StackName}-cp-2-c8xlarge
      VpcConfig:
        SubnetIds:
          - !Select [0, !Ref ManagedInstancesSubnetIds]
          - !Select [1, !Ref ManagedInstancesSubnetIds]
        SecurityGroupIds:
          - !Ref ManagedInstancesSecurityGroupId
      ScalingConfig:
        MaxVCpuCount: 12
        AverageCPUUtilization: 70.0
      InstanceRequirements:
        AllowedTypes:
          - c8g.xlarge  
        Architectures:
          - arm64

  HelloWorldFunctionLMI:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      FunctionName: !Sub ${AWS::StackName}-lmi    
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 2048
      Architectures:
      - arm64
      CapacityProviderConfig:
        Arn: !GetAtt CapacityProvider.Arn
        ExecutionEnvironmentMemoryGiBPerVCpu: 2
        PerExecutionEnvironmentMaxConcurrency: 64
      FunctionScalingConfig:
        MinExecutionEnvironments: 1
        MaxExecutionEnvironments: 4
      Environment:
        Variables:
          RUST_LOG: info
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref HelloWorldApi
            Path: /lmi/2048/hello
            Method: get

Outputs:
  HelloWorldApi512Endpoint:
    Description: API Gateway endpoint URL for prod stage for the 512 MB Hello World function
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod/default/512/hello"
  HelloWorldApi128Endpoint:
    Description: API Gateway endpoint URL for prod stage for the 128 MB Hello World function
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod/default/128/hello"
  HelloWorldApiLMIEndpoint:
    Description: API Gateway endpoint URL for prod stage for LMI Hello World function
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod/lmi/2048/hello"
  HelloWorldFunction512:
    Description: 512 MB Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction512.Arn
  HelloWorldFunction128:
    Description: 128 MB Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction128.Arn
